metronic_v8.0.25/laravel/routes/web.php
<?php

use App\Http\Controllers\Account\SettingsController;
use App\Http\Controllers\Auth\SocialiteLoginController;
use App\Http\Controllers\Documentation\ReferencesController;
use App\Http\Controllers\Logs\AuditLogsController;
use App\Http\Controllers\Logs\SystemLogsController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('index');
});

$menu = theme()->getMenu();
array_walk($menu, function ($val) {
    if (isset($val['path'])) {
        $route = Route::get($val['path'], [PagesController::class, 'index']);

        // Exclude documentation from auth middleware
        if (!Str::contains($val['path'], 'documentation')) {
            $route->middleware('auth');
        }
    }
});

// Documentations pages
Route::prefix('documentation')->group(function () {
    Route::get('getting-started/references', [ReferencesController::class, 'index']);
    Route::get('getting-started/changelog', [PagesController::class, 'index']);
});

Route::middleware('auth')->group(function () {
    // Account pages
    Route::prefix('account')->group(function () {
        Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
        Route::put('settings', [SettingsController::class, 'update'])->name('settings.update');
        Route::put('settings/email', [SettingsController::class, 'changeEmail'])->name('settings.changeEmail');
        Route::put('settings/password', [SettingsController::class, 'changePassword'])->name('settings.changePassword');
    });

    // Logs pages
    Route::prefix('log')->name('log.')->group(function () {
        Route::resource('system', SystemLogsController::class)->only(['index', 'destroy']);
        Route::resource('audit', AuditLogsController::class)->only(['index', 'destroy']);
    });
});

Route::resource('users', UsersController::class);

/**
 * Socialite login using Google service
 * https://laravel.com/docs/8.x/socialite
 */
Route::get('/auth/redirect/{provider}', [SocialiteLoginController::class, 'redirect']);

require __DIR__.'/auth.php';

metronic_v8.0.25/laravel/app/View/Components/BaseLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class BaseLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render()
    {
        if (theme()->getOption('layout', 'base') === 'docs') {
            return view('layout.docs.master');
        }

        return theme()->getView('layout.master');
    }
}

metronic_v8.0.25/laravel/resources/views/pages/documentation/general/datatables/overview/_overview.blade.php
<!--begin::Section-->
<div class="pb-10">
    <!--begin::Heading-->
    <h1 class="anchor fw-bolder mb-5" id="overview-datatables">
        <a href="#overview-datatables"></a>
        DataTables Overview
    </h1>
    <!--end::Heading-->

    <!--begin::Block-->
    <div class="py-5">
        <p>DataTables is a plug-in for the <a href="https://jquery.com/" target="_blank">jQuery</a> Javascript library.
            It is a highly flexible tool, based upon the foundations of progressive enhancement, and will add advanced interaction controls to any HTML table.</p>

        <p>Official documentation of DataTables is available at <a href="https://datatables.net" target="_blank">datatables.net</a></p>
    </div>
    <!--end::Block-->
</div>
<!--end::Section-->

<!--begin::Section-->
<div class="pb-10">
    <!--begin::Heading-->
    <h1 class="anchor fw-bolder mb-5" id="laravel-datatables">
        <a href="#laravel-datatables"></a>
        Laravel DataTables
    </h1>
    <!--end::Heading-->

    <!--begin::Block-->
    <div class="py-5">
        <p>Laravel DataTables is a package that handles the <a href="https://www.datatables.net/manual/server-side" target="_blank">server-side</a> works of <a href="http://datatables.net" target="_blank">DataTables</a> using <a href="http://laravel.com"
                                                                                                                                                                                                                                     target="_blank">Laravel</a>.</p>

        <p>For this package, we use <a href="https://yajrabox.com/docs/laravel-datatables/master/" target="_blank">laravel-datatables</a> and the <a href="https://github.com/yajra/laravel-datatables" target="_blank">Github repository</a></p>
    </div>
    <!--end::Block-->
</div>
<!--end::Section-->

metronic_v8.0.25/laravel/resources/views/pages/documentation/general/datatables/overview/_usage.blade.php
<!--begin::Section-->
<div class="py-10">
    <!--begin::Heading-->
    <h1 class="anchor fw-bolder mb-5" id="usage">
        <a href="#usage"></a>
        Usage
    </h1>
    <!--end::Heading-->

    <!--begin::Block-->
    <div class="py-5">
        Create controller and DataTable class
    </div>
    <!--end::Block-->

    <!--begin::Code-->
    <div class="py-5">
        {{ util()->highlight('
php artisan make:controller UsersController
php artisan datatables:make Users
        ', 'bash') }}
    </div>
    <!--end::Code-->

    <!--begin::Block-->
    <div class="py-5">
        The command above will create a DataTable controller file in <code>app/DataTables/UsersDataTable.php</code>.
    </div>
    <!--end::Block-->

    <!--begin::Code-->
    <div class="py-5">
        {{ util()->highlight('namespace App\DataTables;

use App\User;
use Yajra\DataTables\Html\Button;
use Yajra\DataTables\Html\Column;
use Yajra\DataTables\Html\Editor\Editor;
use Yajra\DataTables\Html\Editor\Fields;
use Yajra\DataTables\Services\DataTable;

class UsersDataTable extends DataTable
{
    /**
     * Build DataTable class.
     *
     * @param mixed $query Results from query() method.
     * @return \Yajra\DataTables\DataTableAbstract
     */
    public function dataTable($query)
    {
        return datatables()
            ->eloquent($query)
            ->addColumn(\'action\', \'users.action\');
    }

    /**
     * Get query source of dataTable.
     *
     * @param \App\User $model
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function query(User $model)
    {
        return $model->newQuery();
    }

    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\DataTables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->setTableId(\'users-table\')
                    ->columns($this->getColumns())
                    ->minifiedAjax()
                    ->dom(\'Bfrtip\')
                    ->orderBy(1)
                    ->buttons(
                        Button::make(\'create\'),
                        Button::make(\'export\'),
                        Button::make(\'print\'),
                        Button::make(\'reset\'),
                        Button::make(\'reload\')
                    );
    }

    /**
     * Get columns.
     *
     * @return array
     */
    protected function getColumns()
    {
        return [
            Column::computed(\'action\')
                  ->exportable(false)
                  ->printable(false)
                  ->width(60)
                  ->addClass(\'text-center\'),
            Column::make(\'id\'),
            Column::make(\'name\'),
            Column::make(\'email\'),
            Column::make(\'created_at\'),
            Column::make(\'updated_at\'),
        ];
    }

    /**
     * Get filename for export.
     *
     * @return string
     */
    protected function filename()
    {
        return \'Users_\' . date(\'YmdHis\');
    }
}
', 'php') }}
    </div>
    <!--end::Code-->

    <!--begin::Block-->
    <div class="py-5">
        Create a new HTTP controller file in <code>app/Http/Controllers/UsersController.php</code>.
    </div>
    <!--end::Block-->

    <!--begin::Code-->
    <div class="py-5">
        {{ util()->highlight('namespace App\Http\Controllers;

use App\DataTables\UsersDataTable;

class UsersController extends Controller
{
    public function index(UsersDataTable $dataTable)
    {
        return $dataTable->render(\'users.index\');
    }
}', 'php') }}
    </div>
    <!--end::Code-->

    <!--begin::Block-->
    <div class="py-5">
        For more information, check on the official <a href="https://yajrabox.com/docs/laravel-datatables/master/quick-starter" target="_blank">documentation site</a>.
    </div>
    <!--end::Block-->

</div>
<!--end::Section-->

metronic_v8.0.25/laravel/resources/views/pages/documentation/general/datatables/overview/overview.blade.php
<x-base-layout>

    {{ theme()->getView('pages/documentation/general/datatables/overview/_overview') }}

    {{ theme()->getView('pages/documentation/general/datatables/overview/_usage') }}

</x-base-layout>