metronic_v8.0.25/laravel/routes/web.php
<?php

use App\Http\Controllers\Account\SettingsController;
use App\Http\Controllers\Auth\SocialiteLoginController;
use App\Http\Controllers\Documentation\ReferencesController;
use App\Http\Controllers\Logs\AuditLogsController;
use App\Http\Controllers\Logs\SystemLogsController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('index');
});

$menu = theme()->getMenu();
array_walk($menu, function ($val) {
    if (isset($val['path'])) {
        $route = Route::get($val['path'], [PagesController::class, 'index']);

        // Exclude documentation from auth middleware
        if (!Str::contains($val['path'], 'documentation')) {
            $route->middleware('auth');
        }
    }
});

// Documentations pages
Route::prefix('documentation')->group(function () {
    Route::get('getting-started/references', [ReferencesController::class, 'index']);
    Route::get('getting-started/changelog', [PagesController::class, 'index']);
});

Route::middleware('auth')->group(function () {
    // Account pages
    Route::prefix('account')->group(function () {
        Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
        Route::put('settings', [SettingsController::class, 'update'])->name('settings.update');
        Route::put('settings/email', [SettingsController::class, 'changeEmail'])->name('settings.changeEmail');
        Route::put('settings/password', [SettingsController::class, 'changePassword'])->name('settings.changePassword');
    });

    // Logs pages
    Route::prefix('log')->name('log.')->group(function () {
        Route::resource('system', SystemLogsController::class)->only(['index', 'destroy']);
        Route::resource('audit', AuditLogsController::class)->only(['index', 'destroy']);
    });
});

Route::resource('users', UsersController::class);

/**
 * Socialite login using Google service
 * https://laravel.com/docs/8.x/socialite
 */
Route::get('/auth/redirect/{provider}', [SocialiteLoginController::class, 'redirect']);

require __DIR__.'/auth.php';

metronic_v8.0.25/laravel/app/Models/UserInfo.php
<?php

namespace App\Models;

use App\Core\Traits\SpatieLogsActivity;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class UserInfo extends Model
{
    use SpatieLogsActivity;

    /**
     * Prepare proper error handling for url attribute
     *
     * @return string
     */
    public function getAvatarUrlAttribute()
    {
        // if file avatar exist in storage folder
        $avatar = public_path(Storage::url($this->avatar));
        if (is_file($avatar) && file_exists($avatar)) {
            // get avatar url from storage
            return Storage::url($this->avatar);
        }

        // check if the avatar is an external url, eg. image from google
        if (filter_var($this->avatar, FILTER_VALIDATE_URL)) {
            return $this->avatar;
        }

        // no avatar, return blank avatar
        return asset(theme()->getMediaUrlPath().'avatars/blank.png');
    }

    /**
     * User info relation to user model
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Unserialize values by default
     *
     * @param $value
     *
     * @return mixed|null
     */
    public function getCommunicationAttribute($value)
    {
        // test to un-serialize value and return as array
        $data = @unserialize($value);
        if ($data !== false) {
            return $data;
        } else {
            return null;
        }
    }
}

metronic_v8.0.25/laravel/resources/views/layout/demo7/aside/__tabs.blade.php
<!--begin::Wrapper-->
<div class="hover-scroll-y mb-10"
    data-kt-scroll="true"
    data-kt-scroll-activate="{default: false, lg: true}"
    data-kt-scroll-height="auto"
    data-kt-scroll-wrappers="#kt_aside_nav"
    data-kt-scroll-dependencies="#kt_aside_logo, #kt_aside_footer"
    data-kt-scroll-offset="0px"
 >
    <!--begin::Nav-->
    <ul class="nav flex-column">
        @foreach(theme()->getOption('menu', 'aside_tabs') as $tab)
            <!--begin::Nav item-->
            <li class="nav-item mb-2" data-bs-toggle="tooltip" data-bs-trigger="hover" data-bs-placement="right" data-bs-dismiss="click" title="{{ $tab['tooltip'] }}">
                <!--begin::Nav link-->
                <a class="nav-link btn btn-icon btn-active-color-primary btn-color-gray-400 btn-active-light {{ $loop->index === 1 ? 'active' : '' }}" data-bs-toggle="tab"  href="#{{ $tab['link'] }}">
                    {!! theme()->getSvgIcon($tab['icon'], "svg-icon-2x") !!}
                </a>
                <!--end::Nav link-->
            </li>
            <!--end::Nav item-->
        @endforeach
    </ul>
    <!--end::Tabs-->
</div>
<!--end::Nav-->

metronic_v8.0.25/laravel/resources/views/layout/demo7/aside/_base.blade.php
<!--begin::Aside-->
<div
	id="kt_aside"
	class="aside aside-extended bg-white {{ theme()->printHtmlClasses('aside', false) }}"
	data-kt-drawer="true"
	data-kt-drawer-name="aside"
	data-kt-drawer-activate="{default: true, lg: false}"
	data-kt-drawer-overlay="true"
	data-kt-drawer-width="auto"
	data-kt-drawer-direction="start"
	data-kt-drawer-toggle="#kt_aside_toggle"
	>

	<!--begin::Primary-->
	<div class="aside-primary d-flex flex-column align-items-lg-center flex-row-auto">
		<!--begin::Logo-->
		<div class="aside-logo d-none d-lg-flex flex-column align-items-center flex-column-auto py-10" id="kt_aside_logo">
			<a href=" {{ theme()->getPageUrl('index') }}">
				<img alt="Logo" src=" {{ asset(theme()->getMediaUrlPath() . 'logos/logo-demo7.svg') }}" class="h-30px"/>
			</a>
		</div>
		<!--end::Logo-->

		<!--begin::Nav-->
		<div class="aside-nav d-flex flex-column align-items-center flex-column-fluid w-100 pt-5 pt-lg-0" id="kt_aside_nav">
			 {{ theme()->getView('layout/aside/__tabs') }}
		</div>
		<!--end::Nav-->

		<!--begin::Footer-->
		<div class="aside-footer d-flex flex-column align-items-center flex-column-auto" id="kt_aside_footer">
			<!--begin::Quick links-->
			<div class="d-flex align-items-center mb-2">
				<!--begin::Menu wrapper-->
				<div class="btn btn-icon btn-active-color-primary btn-color-gray-400 btn-active-light"
					data-kt-menu-trigger="click"
					data-kt-menu-overflow="true"
					data-kt-menu-placement="top-start"
					data-bs-toggle="tooltip"
					data-bs-placement="right"
					data-bs-dismiss="click"
					title="Quick links"
				>
					{!! theme()->getSvgIcon("icons/duotune/general/gen022.svg", "svg-icon-2 svg-icon-lg-1") !!}
				</div>

				 {{ theme()->getView('partials/topbar/_quick-links-menu', array('quick-bg' => 'misc/dropdown-header-bg.png')) }}
				<!--end::Menu wrapper-->
			</div>
			<!--end::Quick links-->

			<!--begin::Notifications-->
			<div class="d-flex align-items-center mb-2">
				<!--begin::Menu wrapper-->
				<div class="btn btn-icon btn-active-color-primary btn-color-gray-400 btn-active-light"
					data-kt-menu-trigger="click"
					data-kt-menu-overflow="true"
					data-kt-menu-placement="top-start"
					data-bs-toggle="tooltip"
					data-bs-placement="right"
					data-bs-dismiss="click"
					title="Notifications">
					{!! theme()->getSvgIcon("icons/duotune/general/gen025.svg", "svg-icon-2 svg-icon-lg-1") !!}
				</div>

				 {{ theme()->getView('partials/topbar/_notifications-menu', array('notifications-bg' => 'misc/dropdown-header-bg.png')) }}
				<!--end::Menu wrapper-->
			</div>
			<!--end::Notifications-->

			<!--begin::Activities-->
			<div class="d-flex align-items-center mb-3">
				<!--begin::Drawer toggle-->
				<div class="btn btn-icon btn-active-color-primary btn-color-gray-400 btn-active-light"
				data-kt-menu-trigger="click"
				data-kt-menu-overflow="true"
				data-kt-menu-placement="top-start"
				data-bs-toggle="tooltip"
				data-bs-placement="right"
				data-bs-dismiss="click"
				title="Activity Logs"
				id="kt_activities_toggle">
					{!! theme()->getSvgIcon("icons/duotune/general/gen032.svg", "svg-icon-2 svg-icon-lg-1") !!}
				</div>
				<!--end::drawer toggle-->
			</div>
			<!--end::Activities-->

			<!--begin::User-->
			<div class="d-flex align-items-center mb-10" id="kt_header_user_menu_toggle">
				<!--begin::Menu wrapper-->
				<div class="cursor-pointer symbol symbol-40px"
				data-kt-menu-trigger="click"
				data-kt-menu-overflow="true"
				data-kt-menu-placement="top-start"
				data-bs-toggle="tooltip"
				data-bs-placement="right"
				data-bs-dismiss="click"
				title="User profile"
				>
					<img src=" {{ auth()->user()->avatar_url }}" alt="metronic"/>
				</div>

				 {{ theme()->getView('partials/topbar/_user-menu', array('language-menu-placement' => 'right-end', 'subscription-menu-placement' => 'right-end')) }}
				<!--end::Menu wrapper-->
			</div>
			<!--end::User-->
		</div>
		<!--end::Footer-->
	</div>
	<!--end::Primary-->

	@if(theme()->getOption('layout', 'aside/secondary-display') === true)
		<!--begin::Secondary-->
		<div class="aside-secondary d-flex flex-row-fluid">
			<!--begin::Workspace-->
			<div class="aside-workspace my-5 p-5" id="kt_aside_wordspace">
				 {{ theme()->getView('layout/aside/__tab-contents/_base') }}
			</div>
			<!--end::Workspace-->
		</div>
		<!--end::Secondary-->

		<!--begin::Aside Toggle-->
		<button class="btn btn-sm btn-icon btn-white btn-active-primary position-absolute translate-middle start-100 end-0 bottom-0 shadow-sm d-none d-lg-flex  {{ theme()->printHtmlClasses('asideToggle', false) }}"
			data-kt-toggle="true"
			data-kt-toggle-state="active"
			data-kt-toggle-target="body"
			data-kt-toggle-name="aside-minimize"

			style="margin-bottom: 1.35rem">

			{!! theme()->getSvgIcon("icons/duotune/arrows/arr063.svg", "svg-icon-2 rotate-180") !!}
		</button>
		<!--end::Aside Toggle-->
	@endif
</div>
<!--end::Aside-->